"""initial_migration

Revision ID: 67b896021b9d
Revises: 
Create Date: 2026-05-13 20:19:51.394017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67b896021b9d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heroes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('hp', sa.Integer(), nullable=True),
        sa.Column('max_hp', sa.Integer(), nullable=True),
        sa.Column('atk', sa.Integer(), nullable=True),
        sa.Column('defense', sa.Integer(), nullable=True),
        sa.Column('gold', sa.Integer(), nullable=True),
        sa.Column('potions', sa.Integer(), nullable=True),
        sa.Column('level', sa.Integer(), nullable=True),
        sa.Column('exp', sa.Integer(), nullable=True),
        sa.Column('exp_to_next', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heroes_id'), 'heroes', ['id'], unique = False)
    op.create_index(op.f('ix_heroes_name'), 'heroes', ['name'], unique = True)

    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('hashed_password', sa.String(), nullable=True),
        sa.Column('is_active', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name = 'users')
    op.drop_index(op.f('ix_users_id'), table_name = 'users')
    op.drop_table('users')
    op.drop_index(op.f('ix_heroes_name'), table_name='heroes')
    op.drop_index(op.f('ix_heroes_id'), table_name='heroes')
    op.drop_table('heroes')
    # ### end Alembic commands ###
