"""add-discription-to-heroes

Revision ID: b6988b6cb4e9
Revises: 67b896021b9d
Create Date: 2026-05-13 20:33:25.441429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6988b6cb4e9'
down_revision: Union[str, Sequence[str], None] = '67b896021b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heroes', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heroes', 'description')
    # ### end Alembic commands ###
